#!/bin/bash

target="tools/phpdoc-markdown-public"

dir=$(pwd)

# Install if missing
if [ -z "$(ls -A $target)" ]; then
    git submodule update --init --recursive
fi

cd $target

if [ -z "$(ls -A vendor)" ]; then
    # composer install 
    $dir/php /usr/local/bin/composer install
fi

cd ../..

# phpdoc command
./php $target \
    --directory=src/ \
    --target=api_reference \
    --template="tools/phpdoc-markdown-public/data/templates/markdown-public" \
    --title="Specify the Title you want here"
