#!/bin/bash

app_dir=$(pwd)
script_dir=$(dirname $(readlink -f "$0"))
# target=$script_dir"/tools/phpdoc-markdown-public/"
target=$script_dir"/tools/phpdoc-md/"

# Install if missing
if [ -z "$(ls -A $target)" ]; then
    git submodule update --init --recursive
fi

if [ -z "$(ls -A $target/vendor)" ]; then
    # composer install 
    cd $target
    $app_dir/composer install
    cd $app_dir
fi

# phpdoc command
# $app_dir/php 7.3 ./tools/phpdoc-markdown-public/vendor/bin/phpdoc \
    # --directory=src/ \
    # --target=api_reference \
    # --template="./tools/phpdoc-markdown-public/data/templates/markdown-public" 

./php $target/bin/phpdoc \
    --directory=src/ \
    --target=api_reference \
    --template="xml" \
    --title="Specify the Title you want here"

$app_dir/php 7.3 $target/bin/phpdocmd api_reference/structure.xml api_reference
