#!/bin/bash

dir=$(dirname $(readlink -f "$0"))
target=$dir"/tools/7to5"


# Install if missing
if [ -z "$(ls -A $target)" ]; then
    git submodule update --init --recursive
fi

if [ -z "$(ls -A $target/vendor)" ]; then
    # composer install 
    $dir/php /usr/local/bin/composer install
fi

./php 7.3 $target/php7to5 convert src/ src_5.6 --overwrite
